### ISSUE TITLE
Force power skill not rolling correct dice

### ISSUE THREAD

**Issue by Orta15a** [teaseal/swffg#6]
Hello,

When adding a force power, for example if using the Coercion skill it does not roll the correct amount of dice for that skill when clicking the power. It seems that it has an upgrade that should not be here.
Could be replicated in the test game with "Triju Jusc" and his "Taco-lightning"

**Comment by teaseal** [comment]
I originally thought this was part of a bigger issue, but it looks like Coercion was pointing towards the wrong characteristic. This was an issue from the old sheet that should now be fixed.
